import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import NavBar from "../utils/nav_var"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav
          style={{
            borderBottom: "1px solid #ddd",
            padding: "10px 20px",
            display: "flex",
            flexDirection: "column",
            gap: "20px",
            size: "20px",
          }}
        >
          <h1 style={{ textAlign: "center", magin: "10px" }}>ToDoList</h1>
          <div
            style={{
              display: "flex",
              justifyContent: "space-around",
            }}
          >
            <NavBar></NavBar>
          </div>
        </nav>
        <div> {children}</div>
      </body>
    </html>
  )
}
